# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'us-central1.pkg.dev/qwiklabs-gcp-01-ec2fbed32c6e/quiz:${COMMIT_SHA}', '.']
# # deploy container image to GKE
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['push', 'us-central1.pkg.dev/qwiklabs-gcp-01-ec2fbed32c6e/quiz:${COMMIT_SHA}']
# images: ['us-central1.pkg.dev/qwiklabs-gcp-01-ec2fbed32c6e/quiz:${COMMIT_SHA}']

# # deploy container image to  GKE
# # - name: "gcr.io/cloud-builders/gke-deploy"
# #   args:
# #   - run
# #   - --filename=deployment.yaml
# #   - --image=us-central1.pkg.dev/qwiklabs-gcp-01-ec2fbed32c6e/quiz:$COMMIT_SHA
# #   - --location=us-central1
# #   - --cluster='cluster-1'

# options:
#   logging: CLOUD_LOGGING_ONLY


steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'global-docker.pkg.dev/qwiklabs-gcp-00-7f0b0ac5adba/quiz/$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'global-docker.pkg.dev/qwiklabs-gcp-00-7f0b0ac5adba/quiz/$COMMIT_SHA']
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=deployment.yaml
  - --image=global.pkg.dev/qwiklabs-gcp-00-7f0b0ac5adba/quiz:$COMMIT_SHA
  - --location=global
  - --cluster='cluster-1'
images: ['global-docker.pkg.dev/qwiklabs-gcp-00-7f0b0ac5adba/quiz/$COMMIT_SHA']

options:
  logging: CLOUD_LOGGING_ONLY
