steps:
# build the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_ZONE}-docker.pkg.dev/${_PROJECT}/quiz/${_VERSION}', '.']
  a
  # push the image to artifact registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_ZONE}-docker.pkg.dev/${_PROJECT}/quiz/${_VERSION}']
  # deploy container image to  GKE 
- name: "gcr.io/cloud-builders/kubectl"
  args:
  - 'apply'
  - '-f'
  - 'kubernetes/'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
  # - run
  # - deploy
  # - quiz-frontend
  # # - --filename=deployment.yaml
  # - --image=${_ZONE}.pkg.dev/${_PROJECT}/quiz:${_VERSION}
  # - --location=${_ZONE}
  # - --cluster='cluster-1'



#Update the container image using kubectl set
# - name: 'gcr.io/cloud-builders/kubectl'
#   args:
#   - 'set'
#   - 'image'
#   - 'deployment/${_DEPLOYMENTNAME}'
#   - '${_CONTAINERNAME}=gcr.io/${_PROJECT}/${_CONTAINERNAME}:${_VERSION}'
#   env:
#   - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'
  
# images: ['us-west1-docker.pkg.dev/qwiklabs-gcp-03-33784ec14891/quiz/${_VERSION}']

substitutions:
#     #GCP Specific configuration. Please DON'T change anything
    _ZONE: us-west1
    _GKE_CLUSTER: cluster-1
    
#     #Repository Specific configuration. DevOps can change this settings
    _DEPLOYMENTNAME: deployment.yaml
    _CONTAINERNAME: quiz-frontend
#     _REPO_NAME: cicd-service
    
    _PROJECT: qwiklabs-gcp-04-1fd93e1489d6
    _VERSION: v1.0
    
options:
    substitution_option: 'ALLOW_LOOSE'
    logging: CLOUD_LOGGING_ONLY
